services:
  - type: web
    name: student-performance-app
    env: docker
    plan: free
    branch: main
    region: oregon
    repo: https://github.com/BhargavaKakkera/Student_performance_Indicator
    autoDeploy: true
